# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
array = np.array([4,8,3,1,0])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
sorted_array = np.sort(array)
print("sorted array:", sorted_array)

sorted array: [0 1 3 4 8]


# Problem 2

In [14]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
import numpy as np
array1 = np.array([10,15,30,45,60])
print("array:", array1)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
array2 = np.arange(5,16)
print("array2:", array2)
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
array3 = np.arange(50,101,5)
print("array3:", array3)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
array4 = np.zeros(10)
print("array4:", array4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
array5 = np.ones(10)
print("array5:", array5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
array6 = np.linspace(0,100,5)
print("array6:", array6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
array7 = np.random.randint(10,31)
print("array7:", array7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
array8 = np.random.uniform(-1,1)
print("array8:", array8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matrix = np.random.randint(10,51, size=(3,5))
print("matrix:", matrix)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
rows, cols = matrix.shape
print("satır sayısı:", rows)
print("sütun sayısı:",cols)
print("toplam:", rows +cols)


# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
max_value = matrix.max()
min_value = matrix.min()
mean_value = matrix.mean()

print("max value:", max_value)
print("min value:", min_value)
print("mean value:", mean_value)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
max_index = np.unravel_index(matrix.argmax(), matrix.shape)
print("max index:", max_index)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
array_13 = np.arange(10,21)
print("first 3 value:", array_13[:3])


# 14- Üretilen dizinin elemanlarını tersten yazdırın.
array14 = np.arange(10,21)
print("reversed:", array14[::-1])


# 15- Üretilen matrisin ilk satırını seçiniz.
first_row = matrix[0,:]
print("first row:", first_row)

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
element = matrix[1,2]
print("second row third column:", element)


# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
first_elements = matrix[:,0]
print("first elements:", first_elements)

# 18- Üretilen matrisin her bir elemanının karesini alınız.
squared_matrix = matrix ** 2
print("squares of all:", squared_matrix)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matrix19 = np.random.randint(-50,51, size=(3,5))
print("matrix19:", matrix19)
positive_even_elements = matrix19[(matrix19>0)& (matrix19%2==0)]
print("positive even nums:", positive_even_elements)

array: [10 15 30 45 60]
array2: [ 5  6  7  8  9 10 11 12 13 14 15]
array3: [ 50  55  60  65  70  75  80  85  90  95 100]
array4: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
array5: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
array6: [  0.  25.  50.  75. 100.]
array7: 28
array8: 0.6268813754285703
matrix: [[15 25 17 23 18]
 [12 44 49 32 34]
 [46 32 23 17 12]]
satır sayısı: 3
sütun sayısı: 5
toplam: 8
max value: 49
min value: 12
mean value: 26.6
max index: (np.int64(1), np.int64(2))
first 3 value: [10 11 12]
reversed: [20 19 18 17 16 15 14 13 12 11 10]
first row: [15 25 17 23 18]
second row third column: 49
first elements: [15 12 46]
squares of all: [[ 225  625  289  529  324]
 [ 144 1936 2401 1024 1156]
 [2116 1024  529  289  144]]
matrix19: [[ 48 -22  18  -4 -20]
 [ -9   6  12  28 -29]
 [ 15  22  -3   6  37]]
positive even nums: [48 18  6 12 28 22  6]
