# Problem 1

In [10]:
# 1 - numpy kütüphanesini import edin
import numpy as np # type: ignore

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matrix = np.random.randint(0,10, size=(5,))
print("matris: ", matrix)


# 3 - matris'in boyutunu öğrenin
print("matris boyutu:" ,matrix.shape)

# 4 - matris'i yeniden boyutlandırın
reshaped_matrix = matrix.reshape((5,1))

# 5 - matris'in boyut sayısını öğrenin
print(reshaped_matrix.ndim)


matris:  [5 3 5 7 1]
matris boyutu: (5,)
2


# Problem 2

In [14]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
import numpy as np 
tek_sayilar = np.array([1,3,5,7,9] )
matrix = np.random.choice(tek_sayilar, (3,3))
print("matris:" , matrix)

# 2 - Oluşturduğunuz matrisi parçalayın

parca = np.split(matrix, matrix.shape[0])
print("parçalanmış matris:", parca)

# 3 - Parçalanmış matrisleri birleştirin
birlestir = np.concatenate(parca)
print("birleşmiş matris:", birlestir)



matris: [[5 3 7]
 [3 3 5]
 [3 5 7]]
parçalanmış matris: [array([[5, 3, 7]]), array([[3, 3, 5]]), array([[3, 5, 7]])]
birleşmiş matris: [[5 3 7]
 [3 3 5]
 [3 5 7]]


# Problem 3

In [19]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
import numpy as np
import random
numbers = list(range(5,101,2))
random_nums = random.sample(numbers,10)
matrix = np.array(random_nums).reshape(2,5)
print("matris:" , matrix)

# 2 - matris'in özelliklerini inceleyin

print("Matrix shape:", matrix.shape)
print("Matrix size:", matrix.size)




matris: [[21 61 37 87 53]
 [69 15 73 71 99]]
Matrix shape: (2, 5)
Matrix size: 10
